export HYDRACTL_USERNAME="hydra"
#HYDRACTL_PASSWORD for HYDRACTL_USERNAME needs to be setup also, do not use this file in order not to accidentally saving to public repo
export TOKENFILE="./tokenfile"
export TESTREPO="tiiuae/ghaf"
export ORGANIZATION="tiiuae"
export BUILDPRSFILE="pr2_data"
export BUILDCHANGEDPRSFILE="pr2_changed_data"
export HYDRACTL="../hydractl/hydractl.py" 
export EXT_PORT="3032"
export RUNDELAY="15" 
